#!/usr/bin/env bash

# Install script for CuriOS dotfiles as an NixOS package.
# This script install the dotfiles from https://github.com/VideoCurio/nixos-dotfiles
# Made for Linux and a COSMIC desktop environment.

set -eu

#------------- Variables init
readonly SCRIPT_VERSION="0.5";
VERBOSE=0;
LOCALE_KEYBOARD="us";
SCRIPT_PATH="$(dirname "$0")"

#------------- Print help function
usage ()
{
  echo -e "
Usage: curios-dotfiles [options] <directory>
  Where,
    directory: Valid directory to copy the dotfiles into, like '/home/<user>' or '/etc/skel'.";

  cat << EOF

  Options:
     -h, --help         Print this message.
     --lang LANG        Preset COSMIC keyboard layout, "us" by default.
     -v, --verbose      Print more information.
     --version          Print version number and exit.

  Examples:
    Install dotfiles into home directory of user 'nixos' with French keyboard:
      curios-dotfiles --lang fr /home/nixos/
    Install as a skeleton for future user home directory:
      curios-dotfiles /etc/skel/
EOF
  exit;
}

#------------- Scripts arguments parse options
ARGS=$(getopt --longoptions="verbose,version,help,lang:" --name "$0" --options ":hv" -- "$@")
if [ $# -lt 1 ]; then
  usage
fi;

INSTALL_DIR="${!#}"

eval set -- "$ARGS"

while true; do
  case "$1" in
    -v | --verbose)
      VERBOSE=1
      shift
      ;;
    -h | --help)
      usage
      ;;
    --lang)
      LOCALE_KEYBOARD="$2"
      shift 2
      ;;
    --version)
      echo "$SCRIPT_VERSION"
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      break
      ;;
  esac
done

#------------- Check <directory>
if [ ! -d "$INSTALL_DIR" ]; then
  printf "\e[31mDirectory argument is invalid!\e[0m\n"
  exit 2
fi

if [ $VERBOSE -eq 1 ]; then
  echo "path: $SCRIPT_PATH"
  echo "<directory>: $INSTALL_DIR"
  echo "--lang: $LOCALE_KEYBOARD"
  echo "--verbose: $VERBOSE"
fi

printf "\e[32m Installing VideoCurio dotfiles...\e[0m\n"

#------------- Check curios-dotfiles files
curios_dotfiles_path=$(nix-store --query --outputs $(which curios-dotfiles))
curios_dotfiles_path=$(realpath "$curios_dotfiles_path"/share)

if [ ! -d "$curios_dotfiles_path" ]; then
  printf "\e[31m curios-dotfiles package not found!\e[0m\n"
  exit 1
fi

if [ $VERBOSE -eq 1 ]; then
  printf "curios-dotfiles package share path: %s\n" "$curios_dotfiles_path"
fi

#------------- Copying dotfiles into INSTALL_DIR
install -D -m 644 -t "$INSTALL_DIR" "$curios_dotfiles_path"/.zshrc
install -D -m 644 -t "$INSTALL_DIR" "$curios_dotfiles_path"/.zshrc-ai.plugin.zsh
cp -r "$curios_dotfiles_path"/.config/ "$INSTALL_DIR"
chmod -R u+w "$INSTALL_DIR"/.config/

#------------- Update COSMIC keyboard layout
sed "s/layout: \".*/layout: \"${LOCALE_KEYBOARD}\",/g" -i "$INSTALL_DIR"/.config/cosmic/com.system76.CosmicComp/v1/xkb_config

printf "\e[32mDotfiles installation done.\e[0m\n"
