# Custom alacritty terminal configuration
[window]
opacity = 0.95

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "SemiBold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

# GNOME terminal Dark
[colors.primary]
background = '#212121'
foreground = '#d0cfcc'

[colors.normal]
black = '#171421'
red = '#c01c28'
green = '#26a269'
yellow = '#a2734c'
blue = '#12488b'
magenta = '#a347ba'
cyan = '#2aa1b3'
white = '#d0cfcc'

[colors.bright]
black = '#5e5c64'
red = '#f66151'
green = '#33d17a'
yellow = '#e9ad0c'
blue = '#2a7bde'
magenta = '#ff06b5'
cyan = '#33c7de'
white = '#ffffff'
